[package]
name = "k0"
version = "0.1.0"
authors = ["Ian Denhardt <ian@zenhack.net>"]
build = "build.rs"

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0.0"
bitflags = "0.9.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
