[package]
name = "k0"
version = "0.1.0"
authors = ["Ian Denhardt <ian@zenhack.net>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
