
cat << "EOF"
/* This file was generated by make_isrs.sh; do not modify it manually. */
EOF

# TODO: in theory you can build loops with GAS macros, but I haven't
# figured out how to get it to work yet. Would simplify the build
# slightly.

for i in `seq 0 255`; do
	case $i in
		8|10|11|12|13|14) printf 'isr %d 0\n' $i ;;
		*)                printf 'isr %d 1\n' $i ;;
	esac
done
